# Use postgres/example user/password credentials

services:

  postgres:
    image: postgres
    restart: always

    volumes:
      - pg-data:/var/lib/postgressql/data

    # ports:
    #  - 5432:5432

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: green_hub
      POSTGRES_DB: greenhub_db
    networks:
      - db_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db_network
    depends_on:
      - postgres

  laravel:
    build: ./API
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:80
    networks:
      - db_network


networks:
  db_network:

volumes:
  pg-data:
